apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
  creationTimestamp: "2022-08-02T09:43:54Z"
  generation: 4
  labels:
    app: space-catz-backend-api
  name: space-catz-backend-api
  namespace: default
  resourceVersion: "576218"
  uid: 7bdf5fd3-ed32-4cb2-87e0-62b177fdfe3f
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: space-catz-backend-api
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: space-catz-backend-api
    spec:
      containers:
      - image: ugochukwu15/space-cat-backend:0.0.6.RELEASE
        imagePullPolicy: IfNotPresent
        name: space-cat-backend
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2022-08-03T07:55:16Z"
    lastUpdateTime: "2022-08-03T07:55:16Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2022-08-02T09:43:54Z"
    lastUpdateTime: "2022-08-03T07:55:16Z"
    message: ReplicaSet "space-catz-backend-api-5db45bcbdc" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 4
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1

---

apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
  creationTimestamp: "2022-08-02T09:49:01Z"
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  labels:
    app: space-catz-backend-api
  name: space-catz-backend-api
  namespace: default
  resourceVersion: "37097"
  uid: 2da5b1d3-1b0d-4eea-bf46-bae26d03f431
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.100.5.130
  clusterIPs:
  - 10.100.5.130
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 31882
    port: 4000
    protocol: TCP
    targetPort: 4000
  selector:
    app: space-catz-backend-api
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 35.226.95.214