apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: space-catz-backend-api
  name: space-catz-backend-api
  namespace: default
spec:
  replicas: 1
  minReadySeconds: 45
  selector:
    matchLabels:
      app: space-catz-backend-api
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: space-catz-backend-api
    spec:
      containers:
      - image: ugochukwu15/space-cat-backend:0.0.6.RELEASE
        imagePullPolicy: IfNotPresent
        name: space-cat-backend
      restartPolicy: Always
      terminationGracePeriodSeconds: 30

---

apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  labels:
    app: space-catz-backend-api
  name: space-catz-backend-api
  namespace: default
spec:
  ports:
  - nodePort: 31882
    port: 4000
    protocol: TCP
    targetPort: 4000
  selector:
    app: space-catz-backend-api
  sessionAffinity: None
  type: LoadBalancer